/* PUSH */
let OVERHEAD_PRESS = "Overhead Press";
let INCLINE_BENCH_PRESS = "Incline Bench Press";
let TRICEP_PUSH_DOWN = "Tricep Push Down";
let CABLE_CROSSOVER = "Cable Crossover";
let UPWARD_CABLE_CROSSOVER = "Upward Cable Crossover";
let BENCH_PRESS = "Bench Press";
let DUMBBELL_SHOULDER_PRESS = "Dumbbell Shoulder Press";
let TRICEP_DIP = "Tricep Dip";
let MACHINE_CHEST_FLY = "Machine Chest Fly";
let OVERHEAD_CABLE_EXTENSION = "Overhead Cable Extension";
let LATERAL_RAISE = "Lateral Raise";
let MACHINE_SHOULDER_PRESS = "Machine Shoulder Press";
let SINGLE_CABLE_EXTENSION = "Single Cable Extension";
let CLOSE_GRIP_DUMBBELL_PRESS = "Close Grip Dumbbell Press";
let MACHINE_TRICEP_EXTENSION = "Machine Tricep Extension";
let DUMBBELL_TRICEP_EXTENSION = "Dumbbell Tricep Extension";
let DUMBBELL_INCLINE_BENCH_PRESS = "Dumbbell Incline Bench Press";
let CABLE_LATERAL_RAISE = "Cable Lateral Raise";
let TRICEP_ROPE_PUSH_DOWN = "Tricep Rope Push Down";

/* PULL */
let DEADLIFT = "Deadlift";
let BARBELL_ROW = "Barbell Row";
let PULL_UP = "Pull-Up";
let DUMBBELL_ROW = "Dumbbell Row";
let WIDE_GRIP_PULL_DOWN = "Wide Grip Pull Down";
let BARBELL_BICEP_CURL = "Barbell Bicep Curl";
let MACHINE_PREACHER_CURL = "Machine Preacher Curl";
let CABLE_ROW = "Cable Row";
let BARBELL_SHRUG = "Barbell Shrug";
let DUMBBELL_CURL = "Dumbbell Curl";
let FACE_PULL = "Face Pull";
let CABLE_BICEP_CURL = "Cable Bicep Curl";

/* Legs */
let BARBELL_SQUAT = "Barbell Squat";
let DUMBBELL_SPLIT_SQUAT = "Dumbbell Split Squat";
let ROMANIAN_DEADLIFT = "Romanian Deadlift";
let CALF_RAISE = "Calf Raise";
let LEG_EXTENSION = "Leg Extension";

/* Abs */
let CABLE_AB_CURL = "Cable Ab Curl";
let HALF_LEG_RAISE = "Half Leg Raise";
let FULL_LEG_RAISE = "Full Leg Raise";

const movements = [
OVERHEAD_PRESS, INCLINE_BENCH_PRESS, TRICEP_PUSH_DOWN, CABLE_CROSSOVER,
UPWARD_CABLE_CROSSOVER, BENCH_PRESS, DUMBBELL_SHOULDER_PRESS, TRICEP_DIP,
MACHINE_CHEST_FLY, OVERHEAD_CABLE_EXTENSION, LATERAL_RAISE, MACHINE_SHOULDER_PRESS,
SINGLE_CABLE_EXTENSION, CLOSE_GRIP_DUMBBELL_PRESS, MACHINE_TRICEP_EXTENSION,
DUMBBELL_TRICEP_EXTENSION, DUMBBELL_INCLINE_BENCH_PRESS, CABLE_LATERAL_RAISE, TRICEP_ROPE_PUSH_DOWN,

BARBELL_ROW, PULL_UP, DUMBBELL_ROW, WIDE_GRIP_PULL_DOWN, BARBELL_BICEP_CURL,
MACHINE_PREACHER_CURL, CABLE_ROW, BARBELL_SHRUG, DUMBBELL_CURL, FACE_PULL,
CABLE_BICEP_CURL, DEADLIFT,

BARBELL_SQUAT, DUMBBELL_SPLIT_SQUAT, ROMANIAN_DEADLIFT, CALF_RAISE, LEG_EXTENSION,

CABLE_AB_CURL, HALF_LEG_RAISE, FULL_LEG_RAISE ]

export default movements